# Generated by Django 5.2.2 on 2025-06-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sio2', models.FloatField()),
                ('fe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SamosvalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Samosval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('current_load', models.FloatField()),
                ('ruda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyfra_app.ruda')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyfra_app.samosvaldescription')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Склад', max_length=50)),
                ('current_quantity', models.FloatField(default=0)),
                ('polygon_wkt', models.TextField()),
                ('ruda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyfra_app.ruda')),
            ],
        ),
    ]
